# OpenAI API Configuration
openai:
  api_key: ${OPENAI_API_KEY}
  model: "gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 1000

# Expert System Configuration
experts:
  sports:
    enabled: true
    cache_enabled: true
    cache_ttl: 3600  # 1 hour
    
  food:
    enabled: true
    cache_enabled: true
    cache_ttl: 3600
    
  ai:
    enabled: true
    cache_enabled: true
    cache_ttl: 3600

# Logging Configuration
logging:
  level: INFO
  format: "%(asctime)s - %(levelname)s - %(message)s"
  
# Cache Configuration
cache:
  enabled: true
  type: "memory"
  max_size: 1000
  ttl: 3600 